<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $documentType }} Report</title>
    <style>
        @page {
            size: A4 landscape;
            margin: 20mm;
        }

        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        .header, .footer {
            text-align: center;
            font-size: 12px;
            color: #666;
        }

        .header {
            margin-bottom: 20px;
        }

        .footer {
            margin-top: 20px;
            position: fixed;
            bottom: 0;
            width: 100%;
        }

        .title {
            font-size: 18px;
            font-weight: bold;
            text-align: center;
            margin-bottom: 20px;
        }

        .table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        .table th, .table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        .table th {
            background-color: #f4f4f4;
            font-weight: bold;
        }

        .metadata {
            margin-bottom: 20px;
            font-size: 14px;
        }

        .metadata p {
            margin: 5px 0;
        }
    </style>
</head>
<body>
    <div class="header">
        <p>Generated by the Records Office Management System</p>
    </div>

    <div class="title">
        {{ $documentType }} Report
    </div>

    <div class="metadata">
        <p><strong>Generated On:</strong> {{ $generatedDate }}</p>
        <p><strong>Description:</strong> {{ $description }}</p>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Destination</th>
                <th>Subject</th>
                <th>Inclusive Date</th>
                <th>Venue</th>
                <th>Beneficiaries</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($documents as $index => $document)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $document['destination'] }}</td>
                    <td>{{ $document['subject'] }}</td>
                    <td>{{ $document['from_date'] }} - {{ $document['to_date'] }}</td>
                    <td>{{ $document['venue'] }}</td>
                    <td>
                        @if (is_array($document['employee_names']))
                            {{ implode(', ', $document['employee_names']) }}
                        @else
                            {{ $document['employee_names'] }}
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>&copy; {{ now()->year }} Records Office Management System. All rights reserved.</p>
    </div>
</body>
</html>
